2021-08-09 09:07:02,837	INFO services.py:1272 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
create_plots.py:33: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox_inchesstr" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig(output_file, bbox_inchesstr='tight')
Traceback (most recent call last):
  File "create_plots.py", line 40, in <module>
    loadAndPlotResults(csv_path+'fs.csv',              'Mean Squared Error',            img_path+'tutorial7MSE_py.png',     False, 'lower right')
  File "create_plots.py", line 33, in loadAndPlotResults
    plt.savefig(output_file, bbox_inchesstr='tight')
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/matplotlib/image.py", line 1605, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/PIL/Image.py", line 2148, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'images/tutorial7MSE_py.png'
2021-08-09 12:41:23,591	INFO services.py:1272 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
create_plots.py:33: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox_inchesstr" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig(output_file, bbox_inchesstr='tight')
create_plots.py:33: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox_inchesstr" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig(output_file, bbox_inchesstr='tight')
create_plots.py:33: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox_inchesstr" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig(output_file, bbox_inchesstr='tight')
create_plots.py:33: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox_inchesstr" which is no longer supported as of 3.3 and will become an error two minor releases later
  plt.savefig(output_file, bbox_inchesstr='tight')
